pipeline {
    agent any

    stages {

        stage('My_First_Stage') {
            steps {
                echo 'Hello world'
            }
        }

        stage('My_Second_Stage') {
            steps {
                sh '''
                date
                uptime
                whoami
                free -h
                '''
            }
        }
        stage(My_Third_Stage){
            steps {
                sh '''
                date
                cal 
            }
        }

    }
}